resources:
- name: artifactory-resource-source
  type: git
  source: 
    uri: https://github.com/emerald-squad/artifactory-resource.git
    branch: 'master'

- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/artifactory-resource
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: publish
  plan:
  - aggregate:
    - get: artifactory-resource-source
      trigger: true
  - task: get-version
    file: artifactory-resource-source/ci/tasks/get-version.yml
  - put: docker-hub
    params:
      build: artifactory-resource-source
      tag: version/version
      tag_as_latest: true
