resources:
- name: artifactory-resource-source
  type: git
  source: 
    uri: git@github.com:emerald-squad/artifactory-resource.git
    branch: 'master'

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:emerald-squad/artifactory-resource.git
    branch: 'version'
    file: version
    private_key: ((github-key))


- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/artifactory-resource
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:
- name: publish
  plan:
  - aggregate:
    - get: artifactory-resource-source
      trigger: true
    - get: version
      params:
        bump: patch
  - put: docker-hub
    params:
      build: artifactory-resource-source
      tag: version/version
      tag_as_latest: false
  - put: version
    params: 
      file: version/version

- name: promote
  plan:
  - aggregate:
    - get:  artifactory-resource-source
      passed: [ publish ]
    - get: docker-hub
      passed: [ publish ]
      params:
        save: true
  - put: docker-hub
    params:
      load: docker-hub
      tag_as_latest: true

- name: major-bump
  plan:
  - put: version
    params:
      bump: major