resources:
- name: artifactory-resource-source
  type: git
  source: 
    uri: https://github.com/emerald-squad/artifactory-resource.git
    branch: 'master'

- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/artifactory-resource
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:
- name: publish
  plan:
  - aggregate:
    - get: artifactory-resource-source
      trigger: true
  - task: get-version
    file: artifactory-resource-source/ci/tasks/get-version.yml
  - task: build
    file: artifactory-resource-source/ci/tasks/build.yml
  - put: docker-hub
    params:
      build: build
      tag: version/version
- name: promote
  plan:
  - aggregate:
    - get: artifactory-resource-source
      passed:
      - publish
  - task: get-version
    file: artifactory-resource-source/ci/tasks/get-version.yml
  - task: build
    file: artifactory-resource-source/ci/tasks/build.yml
  - put: docker-hub
    params:
      build: build
      tag: version/version
      tag_as_latest: true
